config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users, only: [:show, :index] do
    put 'add_stocks' => "users#add_stocks"
    get 'delete_stock' => "users#delete_stock"
  end
  resources :stocks, only: [:new, :create]
end

app/models/classes/stocks_graph.rb
class StocksGraph

  def initialize(stocks_name)
    @stocks_name = stocks_name
  end

  def two_year_graphic
    hash = {}

    # fill hash with stock data
    stocks_data.each do |a|
      a.each do |stock|
        #  2 year history stock data
        if Date.parse("#{ stock.trade_date }") > Date.new(Date.today.year - 2, Date.today.mon, Date.today.mday)
          hash["#{stock.trade_date}"] =+ stock.close.to_f
        end
      end
    end

    hash
  end

  def stocks_data
    array = []

    # create yahoo instance
    yahoo_client = YahooFinance::Client.new

    # get stock data by given symbols and fill array with it
    @stocks_name.each do |n|
      array << yahoo_client.historical_quotes(n, { raw: false, period: :monthly } )
    end
    array
  end

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def yahoo_stock_data
    yahoo_client = YahooFinance::Client.new
    yahoo_client.quotes(current_user.stocks.map { |stock| stock.title } , [:bid, :change, :change_in_percent])
  end

  protected

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :authenticate_user!

  def create
    @stock = Stock.create(stock_params)
    redirect_to :back, success: "Акция добавлена"
  end

  def new
    @stock = Stock.new
  end

  private

  def stock_params
    params.require(:stock).permit(:title)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @data = yahoo_stock_data
    @user = User.find(params[:id])

    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

  def add_stocks
    @stoks = Stock.where(id: params[:stock_ids])
    current_user.stocks << @stoks

    if current_user.save
      redirect_to :back, notice: "Портфель обновлен"
    else
      redirect_to :back, alert: "Произошла ошибка"
    end
  end

  def delete_stock
    @stock = Stock.find params[:stock_id]

    if current_user.stocks.delete(@stock)
      redirect_to :back, notice: "Портфель обновлен"
    else
      redirect_to :back, alert: "Произошла ошибка"
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    if current_user
      redirect_to current_user, notice: "Вы уже в системе."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
  # get array of stock's names
  def user_stocks_title
    current_user.stocks.map { |stock| stock.title }
  end
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      - unless current_user
        = link_to 'Главная', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav.pull-right
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Добавить акции', new_stock_path %></li>
  <li><%= link_to 'Портфель акции', current_user %></li>
  <li><%= link_to 'Редактировать аккаунт', edit_user_registration_path %></li>
  <li><%= link_to 'Выход', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Вход', new_user_session_path %></li>
  <li><%= link_to 'Регистрация', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Finance'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Finance'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == javascript_include_tag "//www.google.com/jsapi", "chartkick"
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/stocks/new.html.slim
h3 Добавить акцию
.row
  .col-md-3
    = simple_form_for @stock do |f|
      = f.input :title, label: "Название"
      = f.button :submit, "Добавить акцию"
    end

app/views/users/_user.html.erb
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.slim
.box
  .col-md-6
    h4.text-center Ваш портфель
    hr
    .stocks
      .row
        - if current_user.stocks.size == 0
          strong.center Необходимо добавить акции в портфель.
        - else
          - current_user.stocks.each_with_index do |stock, index|
            .col-md-4
              strong
                = stock.title
              hr
              p
                | bid:
                = @data[index].bid
              p
                | change:
                = @data[index].change
              p
                | % change:
                = @data[index].change_in_percent
              = link_to "Убрать", user_delete_stock_path(current_user, stock_id: stock.id), class: "btn btn-xs btn-default delete_stock"
              hr
  .col-md-6
    h4.text-center Выбрать акции
    hr
    = form_tag user_add_stocks_path(current_user), method: "PUT" do
      - Stock.all.each do |stock|
        .col-md-4
          .form-group
            = label_tag stock.title, stock.title.upcase
            = check_box_tag 'stock_ids[]', stock.id, current_user.stocks.include?(stock), { multiple: true }
      = submit_tag 'Добавить в портфель', class:"add_stocks"
.row
  .col-md-12.graphic
    h4.text-center Стоимость портфеля за 2 года.
    hr
    = line_chart(StocksGraph.new(user_stocks_title).two_year_graphic)

app/views/visitors/index.html.erb
<h2 class="text-center">Просьба войти или зарегистрироваться</h2>